### ISSUE TITLE
Page Template for List of Links

### ISSUE THREAD

**Issue by ninjha01** [ninjha01/nitro-ui#7]
## Component Description
A page template for a list of links
<img width="900" alt="image" src="https://user-images.githubusercontent.com/25281692/199375064-219678d4-419b-4858-88ec-e224cdc6c021.png">

## Style Variants

- [x] Dark Mode
- [x] Light Mode

## Time Estimate
3 hrs

**Comment by digithed** [comment]
@ninjha01 looks like #8 is about to wrap up. Taking on this issue seems like a normal progression

**Comment by ninjha01** [comment]
Go for it!
