### ISSUE TITLE
Page Template for a list of items

### ISSUE THREAD

**Issue by ninjha01** [ninjha01/nitro-ui#8]
## Component Description
Page Template for a list of items
<img width="898" alt="image" src="https://user-images.githubusercontent.com/25281692/199375140-6fd211ff-f23c-451d-ac0e-d7d388327fb7.png">

## Style Variants

- [x] Dark Mode
- [x] Light Mode

## Time Estimate
3 hrs

**Comment by digithed** [comment]
@ninjha01 Maybe I can start on this?

**Comment by ninjha01** [comment]
That sounds good to me!

**Comment by digithed** [comment]
1/2 way point: Light and dark mode for primary intent completed. Added a second theme based around the brand color for light mode under secondary intent. Added control over colors for card descriptions,titles, etc.
